version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./user_service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - ./user_service/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "True"
    depends_on:
      - db
      - redis
    # ports:
    #   - "8000:8000"
    volumes:
      - ./user_service:/app

  celery:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    command: ["celery", "-A", "app", "worker", "-l", "info"]
    env_file:
      - ./user_service/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "True"
      SKIP_MIGRATIONS: "1"
    depends_on:
      - db
      - redis
    volumes:
      - ./user_service:/app

  ai-celery:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.core.celery_app","worker","--concurrency=1","-Q","ai_service_queue","-l","info"]
    env_file:
      - ./ai_service/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://ai_user:ai_pass@ai_postgres:5432/ai_service_db
      REDIS_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      - ai_postgres
      - redis

  flower:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    command: ["celery", "-A", "app", "flower", "--port=5555"]
    env_file:
      - ./user_service/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "True"
      # FLOWER_BASIC_AUTH: ${FLOWER_BASIC_AUTH}
    ports:
      - "5555:5555"
    depends_on:
      - redis

  ai-flower:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.core.celery_app", "flower", "--port=5556"]
    env_file:
      - ./ai_service/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://ai_user:ai_pass@ai_postgres:5432/ai_service_db
      REDIS_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    ports:
      - "5556:5556"
    depends_on:
      - redis
      - ai_postgres

  ai_postgres:
    image: pgvector/pgvector:pg16   # pgvector-enabled image, not plain postgres
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
      POSTGRES_DB: ai_service_db
    ports:
      - "5433:5432"
    volumes:
      - ai_postgres_data:/var/lib/postgresql/data
    
  ai-service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    env_file:
      - ./ai_service/.env
    depends_on:
      - ai_postgres
      - redis
    volumes:
      - ./ai_service:/app
  
  kong:
    image: kong:3.9
    container_name: kong
    restart: unless-stopped
    env_file:
      - ./kong/.env
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled,header_injector
      KONG_LUA_PACKAGE_PATH: /opt/kong/plugins/?.lua;/opt/kong/plugins/?/init.lua;;
    volumes:
      - ./kong/declarative:/kong/declarative:ro
      - ./kong/services:/kong/services:ro
      - ./kong/start-kong.sh:/start-kong.sh:ro
      - ./kong/plugins:/opt/kong/plugins/kong/plugins:ro
    entrypoint:
      - sh
      - /start-kong.sh
    ports:
      - "8000:8000"   # public proxy
      - "8001:8001"   # admin API (dev only — don't expose in prod)
    depends_on:
      - user-service
      - ai-service

volumes:
  postgres_data:
  ai_postgres_data:
