# Generated by Django 6.0.6 on 2026-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('account.email_changed', 'Email Changed'), ('account.email_verified', 'Email Verified'), ('account.password_changed', 'Password Changed'), ('account.password_reset_completed', 'Password Rest Success'), ('account.phone_changed', 'Password Changed'), ('account.phone_verified', 'Password Rest Success'), ('account.register', 'Welcome')], db_index=True, max_length=64),
        ),
    ]
