[pytest]
DJANGO_SETTINGS_MODULE = app.config.test_settings
python_files = test_*.py *_test.py tests.py
addopts = -v --reuse-db --cov=. --cov-report=term-missing --cov-report=html
testpaths = app/apps/