"""added cv_skills table for helping matching jobs

Revision ID: 1c79f9df44c3
Revises: ebe00a3a79b7
Create Date: 2026-08-21 22:34:09.688747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c79f9df44c3'
down_revision: Union[str, Sequence[str], None] = 'ebe00a3a79b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cv_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['master_cv_versions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_id', 'skill_id', name='uq_cv_skills_cv_id_skill_id')
    )
    op.create_index('ix_cv_skills_cv_id', 'cv_skills', ['cv_id'], unique=False)
    op.create_index('ix_cv_skills_skill_id', 'cv_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cv_skills_skill_id', table_name='cv_skills')
    op.drop_index('ix_cv_skills_cv_id', table_name='cv_skills')
    op.drop_table('cv_skills')
    # ### end Alembic commands ###