"""added the job_skills table

Revision ID: 1fa25200ce5e
Revises: 7206374b5c64
Create Date: 2026-08-19 11:59:56.065106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa25200ce5e'
down_revision: Union[str, Sequence[str], None] = '7206374b5c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skills_job_id_skill_id')
    )
    op.create_index('ix_job_skills_job_id', 'job_skills', ['job_id'], unique=False)
    op.create_index('ix_job_skills_skill_id', 'job_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_skills_skill_id', table_name='job_skills')
    op.drop_index('ix_job_skills_job_id', table_name='job_skills')
    op.drop_table('job_skills')
    # ### end Alembic commands ###
