"""removed the cv_template_id from tailored user cv

Revision ID: 25ace1d3a743
Revises: 136d9a7c83d3
Create Date: 2026-09-17 09:37:03.804451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ace1d3a743'
down_revision: Union[str, Sequence[str], None] = '136d9a7c83d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tailored_cvs_cv_template_id_fkey'), 'tailored_cvs', type_='foreignkey')
    op.drop_column('tailored_cvs', 'cv_template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailored_cvs', sa.Column('cv_template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tailored_cvs_cv_template_id_fkey'), 'tailored_cvs', 'cv_templates', ['cv_template_id'], ['id'])
    # ### end Alembic commands ###
