"""added a column in master_cv_versions table name is target_role

Revision ID: 36a8f75d3c41
Revises: 8e45bfa39037
Create Date: 2026-08-20 13:24:34.066459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a8f75d3c41'
down_revision: Union[str, Sequence[str], None] = '8e45bfa39037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_cv_versions', sa.Column('target_role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_cv_versions', 'target_role')
    # ### end Alembic commands ###
