"""add chunks table

Revision ID: 3dd4ffd5e51f
Revises: eabb2273e3b3
Create Date: 2026-10-08 05:48:22.371357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3dd4ffd5e51f'
down_revision: Union[str, Sequence[str], None] = 'eabb2273e3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=True),
    sa.Column('heading_path', sa.String(length=255), server_default='', nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_access_level'), 'chunks', ['access_level'], unique=False)
    op.create_index(op.f('ix_chunks_doc_type'), 'chunks', ['doc_type'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('uq_chunks_document_id_chunk_index', 'chunks', ['document_id', 'chunk_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_chunks_document_id_chunk_index', table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_doc_type'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_access_level'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
