"""create raw_jobs table

Revision ID: 475d41286dc9
Revises: e4ff7240d5c9
Create Date: 2026-08-16 16:12:48.472753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '475d41286dc9'
down_revision: Union[str, Sequence[str], None] = 'e4ff7240d5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', postgresql.ENUM('API', 'ATS_DIRECT', 'SCRAPE', name='source_type'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('employment_type_raw', sa.Text(), nullable=True),
    sa.Column('salary_raw', sa.Text(), nullable=True),
    sa.Column('posted_at_raw', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), server_default='pending', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_name', 'external_id', name='uq_raw_jobs_source')
    )
    op.create_index('idx_raw_jobs_dedup_hash', 'raw_jobs', ['dedup_hash'], unique=False)
    op.create_index('idx_raw_jobs_unprocessed', 'raw_jobs', ['processing_status'], unique=False, postgresql_where=sa.text("processing_status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_raw_jobs_unprocessed', table_name='raw_jobs', postgresql_where=sa.text("processing_status = 'pending'"))
    op.drop_index('idx_raw_jobs_dedup_hash', table_name='raw_jobs')
    op.drop_table('raw_jobs')
    # ### end Alembic commands ###
