"""added master CV versioning table

Revision ID: 47e919b44d85
Revises: 709fc8a43bae
Create Date: 2026-08-10 21:57:44.549487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47e919b44d85'
down_revision: Union[str, Sequence[str], None] = '709fc8a43bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_cv_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_cv_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_cv_id'], ['master_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_cv_id', 'version', name='uq_master_cv_version')
    )
    op.create_index('one_current_version_per_cv', 'master_cv_versions', ['master_cv_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.drop_column('master_cvs', 'embedding')
    op.drop_column('master_cvs', 'parsed_data')
    op.drop_column('master_cvs', 'status')
    op.drop_column('master_cvs', 'is_deleted')
    op.drop_column('master_cvs', 'raw_text')
    op.drop_column('master_cvs', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_cvs', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('master_cvs', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('master_cvs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('master_cvs', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('master_cvs', sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('master_cvs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True))
    op.drop_index('one_current_version_per_cv', table_name='master_cv_versions', postgresql_where=sa.text('is_current = true'))
    op.drop_table('master_cv_versions')
    # ### end Alembic commands ###
