"""added a new table for tailored cv

Revision ID: 5fabb6821d6b
Revises: f1a2b3c4d5e6
Create Date: 2026-09-17 05:39:17.798009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fabb6821d6b'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailored_cvs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tailoring_run_id', sa.UUID(), nullable=False),
    sa.Column('cv_template_id', sa.UUID(), nullable=False),
    sa.Column('tex_content', sa.String(), nullable=False),
    sa.Column('critic_score', sa.Numeric(), nullable=True),
    sa.Column('critic_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_template_id'], ['cv_templates.id'], ),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_cvs_tailoring_run_id'), 'tailored_cvs', ['tailoring_run_id'], unique=True)
    op.drop_constraint(op.f('fk_tailoring_runs_cv_template_id'), 'tailoring_runs', type_='foreignkey')
    op.drop_column('tailoring_runs', 'cv_template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailoring_runs', sa.Column('cv_template_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_tailoring_runs_cv_template_id'), 'tailoring_runs', 'cv_templates', ['cv_template_id'], ['id'])
    op.drop_index(op.f('ix_tailored_cvs_tailoring_run_id'), table_name='tailored_cvs')
    op.drop_table('tailored_cvs')
    # ### end Alembic commands ###
