"""added new field in cv_templates table

Revision ID: 616620b219a4
Revises: fe0f31e9e9b2
Create Date: 2026-09-13 12:05:51.890409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616620b219a4'
down_revision: Union[str, Sequence[str], None] = 'fe0f31e9e9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_templates', sa.Column('status', sa.Enum('pending', 'active', 'failed', name='cv_template_status', native_enum=False, length=20), nullable=False))
    op.add_column('cv_templates', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_templates', 'error_message')
    op.drop_column('cv_templates', 'status')
    # ### end Alembic commands ###
