"""add documents table

Revision ID: 61febb2769c5
Revises: a7f31c9d0e42
Create Date: 2026-10-08 05:31:29.962542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61febb2769c5'
down_revision: Union[str, Sequence[str], None] = 'a7f31c9d0e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('doc_type', postgresql.ENUM('financial', 'employee', 'investor', 'policy', 'other', name='document_doc_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('access_level', postgresql.ENUM('public', 'internal', 'restricted', name='document_access_level'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='document_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('documents')
    for enum_name in ('document_status', 'document_access_level', 'document_doc_type'):
        sa.Enum(name=enum_name).drop(op.get_bind())
