"""added soft delete field

Revision ID: 686457db464b
Revises: a96c8133f06e
Create Date: 2026-08-08 16:26:00.601795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686457db464b'
down_revision: Union[str, Sequence[str], None] = 'a96c8133f06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_cvs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_cvs', 'is_deleted')
    # ### end Alembic commands ###
