"""added deleted_at column in the master_cv

Revision ID: 709fc8a43bae
Revises: 686457db464b
Create Date: 2026-08-08 18:26:35.379203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709fc8a43bae'
down_revision: Union[str, Sequence[str], None] = '686457db464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_cvs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_cvs', 'deleted_at')
    # ### end Alembic commands ###
