"""replaced the reaw_text, embedding, and parsed_data can contain null values

Revision ID: 8763af3e39ed
Revises: b0435f1963a1
Create Date: 2026-08-07 18:01:31.796623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8763af3e39ed'
down_revision: Union[str, Sequence[str], None] = 'b0435f1963a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master_cvs', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master_cvs', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
