"""added the job_chunks table

Revision ID: 8e45bfa39037
Revises: 58c2cb45145c
Create Date: 2026-08-19 20:21:00.912598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '8e45bfa39037'
down_revision: Union[str, Sequence[str], None] = '58c2cb45145c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_chunks_job_id'), 'job_chunks', ['job_id'], unique=False)
    op.create_index('uq_job_chunks_job_id_chunk_index', 'job_chunks', ['job_id', 'chunk_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_job_chunks_job_id_chunk_index', table_name='job_chunks')
    op.drop_index(op.f('ix_job_chunks_job_id'), table_name='job_chunks')
    op.drop_table('job_chunks')
    # ### end Alembic commands ###
