"""added the source_url and salary_period column

Revision ID: 9e2055a65448
Revises: e3e610fe5234
Create Date: 2026-08-18 16:39:28.207772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2055a65448'
down_revision: Union[str, Sequence[str], None] = 'e3e610fe5234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_period', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source_url')
    op.drop_column('jobs', 'salary_period')
    # ### end Alembic commands ###
