"""added a status field

Revision ID: b0435f1963a1
Revises: b6971d8fee7b
Create Date: 2026-08-07 14:54:14.268801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0435f1963a1'
down_revision: Union[str, Sequence[str], None] = 'b6971d8fee7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_cvs', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_cvs', 'status')
    # ### end Alembic commands ###
