"""added the tex_hash fro prevent duplicate templates

Revision ID: b08433ca3ee3
Revises: c7ac2d523470
Create Date: 2026-08-26 13:28:52.767711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08433ca3ee3'
down_revision: Union[str, Sequence[str], None] = 'c7ac2d523470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_templates', sa.Column('tex_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_cv_templates_tex_hash'), 'cv_templates', ['tex_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_templates_tex_hash'), table_name='cv_templates')
    op.drop_column('cv_templates', 'tex_hash')
    # ### end Alembic commands ###
