"""created new table for the company

Revision ID: b7d314c2b95b
Revises: 25df83c24387
Create Date: 2026-08-17 13:26:16.692120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d314c2b95b'
down_revision: Union[str, Sequence[str], None] = '25df83c24387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTO_VERIFIED', 'ADMIN_VERIFIED', 'PENDING_REVIEW', 'REJECTED', name='companystatus'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('verification_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
