"""added the deleted_at field in cv_templates table

Revision ID: b9f7b07041f6
Revises: b08433ca3ee3
Create Date: 2026-08-26 14:49:14.093917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f7b07041f6'
down_revision: Union[str, Sequence[str], None] = 'b08433ca3ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_templates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_templates', 'deleted_at')
    # ### end Alembic commands ###
