"""initial schema

Revision ID: bab6b2ebbee2
Revises: 
Create Date: 2026-08-17 23:39:10.073619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'bab6b2ebbee2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'admin_verified', 'pending_review', 'rejected', name='companystatus'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('verified_website_url', sa.String(), nullable=True),
    sa.Column('verified_linkedin_url', sa.String(), nullable=True),
    sa.Column('verification_reasoning', sa.String(), nullable=True),
    sa.Column('verification_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=True)
    op.create_table('master_cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_cvs_user_id'), 'master_cvs', ['user_id'], unique=False)
    op.create_table('master_cv_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_cv_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='cv_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_cv_id'], ['master_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_cv_id', 'version', name='uq_master_cv_version')
    )
    op.create_index('one_current_version_per_cv', 'master_cv_versions', ['master_cv_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('raw_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', postgresql.ENUM('API', 'ATS_DIRECT', 'SCRAPE', name='source_type'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('employment_type_raw', sa.Text(), nullable=True),
    sa.Column('salary_raw', sa.Text(), nullable=True),
    sa.Column('posted_at_raw', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_name', 'external_id', name='uq_raw_jobs_source')
    )
    op.create_index('idx_raw_jobs_dedup_hash', 'raw_jobs', ['dedup_hash'], unique=False)
    op.create_index('idx_raw_jobs_unprocessed', 'raw_jobs', ['processing_status'], unique=False, postgresql_where=sa.text("processing_status = 'pending'"))
    op.create_index(op.f('ix_raw_jobs_company_id'), 'raw_jobs', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_jobs_company_id'), table_name='raw_jobs')
    op.drop_index('idx_raw_jobs_unprocessed', table_name='raw_jobs', postgresql_where=sa.text("processing_status = 'pending'"))
    op.drop_index('idx_raw_jobs_dedup_hash', table_name='raw_jobs')
    op.drop_table('raw_jobs')
    op.drop_index('one_current_version_per_cv', table_name='master_cv_versions', postgresql_where=sa.text('is_current = true'))
    op.drop_table('master_cv_versions')
    op.drop_index(op.f('ix_master_cvs_user_id'), table_name='master_cvs')
    op.drop_table('master_cvs')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
