"""added job_matches table

Revision ID: be8518b21866
Revises: 1c79f9df44c3
Create Date: 2026-08-24 11:25:33.994944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be8518b21866'
down_revision: Union[str, Sequence[str], None] = '1c79f9df44c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('vector_score', sa.Float(), nullable=True),
    sa.Column('lexical_score', sa.Float(), nullable=True),
    sa.Column('rrf_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('key_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'VIEWED', 'SAVED', 'DISMISSED', 'APPLIED', name='match_status'), nullable=False),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_match_user_job')
    )
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    op.create_index('ix_job_matches_user_score', 'job_matches', ['user_id', 'final_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_matches_user_score', table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
