"""added the new field in raw_jobs table name is company_id for linking the companies

Revision ID: beb48cb33e92
Revises: b7d314c2b95b
Create Date: 2026-08-17 13:30:54.434900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb48cb33e92'
down_revision: Union[str, Sequence[str], None] = 'b7d314c2b95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_jobs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_raw_jobs_company_id'), 'raw_jobs', ['company_id'], unique=False)
    op.create_foreign_key(None, 'raw_jobs', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_raw_jobs_company_id'), table_name='raw_jobs')
    op.drop_column('raw_jobs', 'company_id')
    # ### end Alembic commands ###
