"""added cv_draft table

Revision ID: c90dc0939739
Revises: 5550afc0fa5f
Create Date: 2026-09-14 05:01:11.177291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90dc0939739'
down_revision: Union[str, Sequence[str], None] = '5550afc0fa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_drafts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tailoring_run_id', sa.UUID(), nullable=False),
    sa.Column('cv_template_id', sa.UUID(), nullable=False),
    sa.Column('tex_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_template_id'], ['cv_templates.id'], ),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tailoring_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_drafts')
    # ### end Alembic commands ###
