"""added a new columns in tailored_cvs like render_status, file_s3_key, render_error_message

Revision ID: cdde3385c1fd
Revises: 25ace1d3a743
Create Date: 2026-09-17 10:28:10.875227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cdde3385c1fd"
down_revision: Union[str, Sequence[str], None] = "25ace1d3a743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    render_status_enum = sa.Enum(
        "pending",
        "processing",
        "completed",
        "failed",
        name="cv_render_status",
    )

    # Create PostgreSQL ENUM type first
    render_status_enum.create(
        op.get_bind(),
        checkfirst=True,
    )

    # Add render_status
    op.add_column(
        "tailored_cvs",
        sa.Column(
            "render_status",
            render_status_enum,
            nullable=False,
            server_default="pending",
        ),
    )

    # Add S3 key
    op.add_column(
        "tailored_cvs",
        sa.Column(
            "file_s3_key",
            sa.String(length=500),
            nullable=True,
        ),
    )

    # Add render error message
    op.add_column(
        "tailored_cvs",
        sa.Column(
            "render_error_message",
            sa.String(),
            nullable=True,
        ),
    )

    # Remove default after existing rows are populated
    op.alter_column(
        "tailored_cvs",
        "render_status",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tailored_cvs", "render_error_message")
    op.drop_column("tailored_cvs", "file_s3_key")
    op.drop_column("tailored_cvs", "render_status")
    # ### end Alembic commands ###
