"""added matches column in jobs table

Revision ID: de8fb0f14690
Revises: e86730a1a3f1
Create Date: 2026-08-24 12:18:38.911399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8fb0f14690'
down_revision: Union[str, Sequence[str], None] = 'e86730a1a3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_matches_user_score', 'job_matches', ['user_id', 'final_score'], unique=False)
    op.create_unique_constraint('uq_job_match_user_job', 'job_matches', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_match_user_job', 'job_matches', type_='unique')
    op.drop_index('ix_job_matches_user_score', table_name='job_matches')
    # ### end Alembic commands ###
