"""refactored table and edited company relation ship inside the job table

Revision ID: e3e610fe5234
Revises: 0e5669a3c1d4
Create Date: 2026-08-18 16:06:55.915056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e610fe5234'
down_revision: Union[str, Sequence[str], None] = '0e5669a3c1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
