"""added a embedding field

Revision ID: e4ff7240d5c9
Revises: f225a19f436d
Create Date: 2026-08-11 11:51:46.398851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e4ff7240d5c9'
down_revision: Union[str, Sequence[str], None] = 'f225a19f436d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_cv_versions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_cv_versions', 'embedding')
    # ### end Alembic commands ###
