"""add document types table

Revision ID: eabb2273e3b3
Revises: 61febb2769c5
Create Date: 2026-10-08 05:41:48.212380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabb2273e3b3'
down_revision: Union[str, Sequence[str], None] = '61febb2769c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=True)
    # ### end Alembic commands ###

    document_types = sa.table(
        'document_types',
        sa.column('id', sa.Uuid()),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
    )
    op.bulk_insert(
        document_types,
        [
            {'name': 'financial', 'description': 'Financial statements and reports'},
            {'name': 'employee', 'description': 'Employee records and handbooks'},
            {'name': 'investor', 'description': 'Investor relations documents'},
            {'name': 'policy', 'description': 'Company policies and procedures'},
            {'name': 'other', 'description': None},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM document_types "
        "WHERE name IN ('financial', 'employee', 'investor', 'policy', 'other')"
    )
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.drop_table('document_types')
