"""removed unwanted cv_draft table

Revision ID: efb1676ed224
Revises: fe9636bb8998
Create Date: 2026-09-17 07:13:08.437863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb1676ed224'
down_revision: Union[str, Sequence[str], None] = 'fe9636bb8998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_drafts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_drafts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tailoring_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cv_template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('cv_structure', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cv_template_id'], ['cv_templates.id'], name=op.f('cv_drafts_cv_template_id_fkey')),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], name=op.f('cv_drafts_tailoring_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_drafts_pkey')),
    sa.UniqueConstraint('tailoring_run_id', name=op.f('cv_drafts_tailoring_run_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
