"""create a table such as tailoring_runs, strategy_briefs, evidence_matrices, evidence_items

Revision ID: fe0f31e9e9b2
Revises: b9f7b07041f6
Create Date: 2026-09-13 07:03:26.327056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0f31e9e9b2'
down_revision: Union[str, Sequence[str], None] = 'b9f7b07041f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailoring_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('cv_version_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('evidence_match', 'strategy', 'write', 'critic', name='tailoring_stage'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='tailoring_run_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', 'cv_version_id', name='uq_tailoring_runs_user_job_cv')
    )
    op.create_table('evidence_matrices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tailoring_run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tailoring_run_id')
    )
    op.create_table('strategy_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tailoring_run_id', sa.UUID(), nullable=False),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('section_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lead_experiences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps_to_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords_to_weave', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tailoring_run_id'], ['tailoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tailoring_run_id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_matrix_id', sa.UUID(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('evidence_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_matrix_id'], ['evidence_matrices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_evidence_matrix_id'), 'evidence_items', ['evidence_matrix_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_items_evidence_matrix_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_table('strategy_briefs')
    op.drop_table('evidence_matrices')
    op.drop_table('tailoring_runs')
    # ### end Alembic commands ###
