"""replaced the text field to cv_structure in table tailored_cvs and cv_drafts

Revision ID: fe9636bb8998
Revises: 5fabb6821d6b
Create Date: 2026-09-17 06:20:16.769409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe9636bb8998'
down_revision: Union[str, Sequence[str], None] = '5fabb6821d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_drafts', sa.Column('cv_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('cv_drafts', 'tex_content')
    op.add_column('tailored_cvs', sa.Column('cv_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('tailored_cvs', 'tex_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailored_cvs', sa.Column('tex_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tailored_cvs', 'cv_structure')
    op.add_column('cv_drafts', sa.Column('tex_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('cv_drafts', 'cv_structure')
    # ### end Alembic commands ###
