# Generated by Django 6.0.6 on 2026-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('root_task_id', models.CharField(blank=True, max_length=255)),
                ('parent_task_id', models.CharField(blank=True, max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('queue', models.CharField(blank=True, max_length=100)),
                ('worker', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('args', models.JSONField(blank=True, null=True)),
                ('kwargs', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('exception', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='task_monito_status_86a8b3_idx'), models.Index(fields=['task_name'], name='task_monito_task_na_80081c_idx'), models.Index(fields=['created_at'], name='task_monito_created_d38db7_idx')],
            },
        ),
    ]
