# Generated by Django 6.0.6 on 2026-07-07 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('email', 'Email & Password'), ('mobile', 'Mobile & OTP'), ('google', 'Google OAuth')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, help_text='hashed', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_uid', models.CharField(blank=True, help_text="provider's unique user id, e.g. Google 'sub'", max_length=255, null=True)),
                ('provider_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='authenticat_user_id_234b3d_idx'), models.Index(fields=['phone_number'], name='authenticat_phone_n_b784a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'provider'), name='unique_user_provider'), models.UniqueConstraint(fields=('provider', 'provider_uid'), name='unique_provider_account')],
            },
        ),
    ]
