# Generated by Django 6.0.6 on 2026-07-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authmethod',
            name='authenticat_user_id_234b3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='authmethod',
            name='authenticat_phone_n_b784a8_idx',
        ),
        migrations.RemoveConstraint(
            model_name='authmethod',
            name='unique_user_provider',
        ),
        migrations.RemoveConstraint(
            model_name='authmethod',
            name='unique_provider_account',
        ),
        migrations.DeleteModel(
            name='AuthMethod',
        ),
    ]
