# Generated by Django 6.0.6 on 2026-07-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_authmethod_authenticat_user_id_234b3d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('email', 'Email & Password'), ('mobile', 'Mobile & OTP'), ('google', 'Google OAuth')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, help_text='hashed', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('provider_uid', models.CharField(blank=True, help_text="provider's unique user id, e.g. Google 'sub'", max_length=255, null=True)),
                ('provider_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('phone_change', 'Phone Change'), ('magic_link', 'Magic Link')], max_length=30)),
                ('token_hash', models.CharField(help_text='SHA-256 or equivalent hash of the token/OTP.', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='authentication.authmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Token',
                'verbose_name_plural': 'Verification Tokens',
                'db_table': 'verification_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='authmethod',
            index=models.Index(fields=['user_id'], name='authenticat_user_id_234b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='authmethod',
            index=models.Index(fields=['phone_number'], name='authenticat_phone_n_b784a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='authmethod',
            constraint=models.UniqueConstraint(fields=('user_id', 'provider'), name='unique_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='authmethod',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_uid'), name='unique_provider_account'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['user'], name='verificatio_user_id_fa3be4_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['auth_method'], name='verificatio_auth_me_9031a0_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['type'], name='verificatio_type_ba1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['user', 'type'], name='verificatio_user_id_775e7c_idx'),
        ),
    ]
