# Generated by Django 6.0.6 on 2026-07-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authmethod',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameIndex(
            model_name='authmethod',
            new_name='authenticat_user_id_64ea3d_idx',
            old_name='authenticat_user_id_234b3d_idx',
        ),
    ]
