# Generated by Django 6.0.6 on 2026-07-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_user_id_authmethod_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authmethod',
            name='authenticat_phone_n_b784a8_idx',
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('password_reset', 'Password Reset'), (' email_change', 'Email Change'), ('phone_change', 'Phone Change'), ('magic_link', 'Magic Link')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='authmethod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authmethod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='authmethod',
            name='phone_number',
        ),
    ]
