# Generated by Django 6.0.6 on 2026-07-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_authmethod_authenticat_phone_n_b784a8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_change_old', 'Change old Phone'), ('phone_change_new', 'Change new Phone'), ('password_reset', 'Password Reset'), ('email_change_old', 'Old Email Change'), ('email_change_new', 'New Email Change'), ('phone_verification', 'Phone Verification'), ('magic_link', 'Magic Link')], max_length=30),
        ),
    ]
